image:
  file: .gitpod.Dockerfile
tasks:
  - command: sbt ~run
vscode:
  extensions:
    - scala-lang.scala
    - scalameta.metals
    - eamodio.gitlens
    - mhutchie.git-graph
    - ahmadawais.shades-of-purple
    - equinusocio.vsc-material-theme-iconsports:
  - port: 8212
    onOpen: ignore
