image:
  file: .gitpod.Dockerfile
tasks:
  - command: sbt ~run
vscode:
  extensions:
    - scala-lang.scala
    - scalameta.metals
    - eamodio.gitlens
    - mhutchie.git-graphports:
    - ahmadawais.shades-of-purple
port: 8212
    onOpen: ignore
